apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is a configmap Index file </h1>
    </html
---
apiVersion: v1
kind: Secret
metadata:
  name: test-tls
type: kubernetes.io/tls
data:
  tls.crt: MIIDCTCCAfGgAwIBAgIUIpc9R3qm1GBi/aCJdi+koAgAy5gwDQYJKoZIhvcNAQELBQAwFDESMBAGA1UEAwwJbG9jYWxob3N0MB4XDTI1MDUwMzA5MDIyNFoXDTI2MDUwMzA5MDIyNFowFDESMBAGA1UEAwwJbG9jYWxob3N0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0Umui2lQeyKLcH7cJSzS6hfz/AOHw2/V/cJyF2uTC3Nyg72EkMpwRKy5JE4HZIkppcZgXsH5wnMDUOGKhLjobMD9weMcpBnFb1LJ9v+gSI397DZ2Rl3liH8pYXbQ0MIL9nD7T0yuUBPA41k2rUAmmxl3RRxlE7wglPLui5eDXnt0pdQzbGTYxOccKpe+Q+SZrL/xkluLXqfkeu/iAvZHzs7fCWt5+JCDqGOSDFWs6xxgiZL71imw5+R4SOxeg9H4nVMrWZJZ1vXeL6/rCEm8DtmD1d6CMrJD/Qv5YpcXdUqYka4TsEedrjs+PoGoUnl1DLexqbqgwkcSf1X1gbjjlQIDAQABo1MwUTAdBgNVHQ4EFgQUdaXzsuIA2qoofdAD14Jg0CACjzIwHwYDVR0jBBgwFoAUdaXzsuIA2qoofdAD14Jg0CACjzIwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAVJ6NbpPvy1hHOsIhmptYhwrfCwpy7XU2tmRQclMH+RpyEGIcKttdl4GbIRxwDHE6PmIcNvo86+4j3ut92QpLKn9KVxj3M+HeOSf2y3g7Xg3tZ0v/BX1M75cx6Yvi++wNI6avdxAZmg9dj5qIGIGesSTWLPUy9Urc9cIcK1z9u0q65jzb98Vv4OuZTr44n/tT1KLWwwMhkT9RiFe4Oco8vjTylmbWsp3ePmCO7xcmUetlxs7QpbRkiFnd2HLVXCqygLxDfuFJawlMJVnW7vm1WGoYiIrNvQ7T7X7MBwbYTiEeqUylk27c1ZXOVSnBJrY2zNWGvpf4DUXy570J0dTpkw==
  tls.key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDRSa6LaVB7IotwftwlLNLqF/P8A4fDb9X9wnIXa5MLc3KDvYSQynBErLkkTgdkiSmlxmBewfnCcwNQ4YqEuOhswP3B4xykGcVvUsn2/6BIjf3sNnZGXeWIfylhdtDQwgv2cPtPTK5QE8DjWTatQCabGXdFHGUTvCCU8u6Ll4Nee3Sl1DNsZNjE5xwql75D5Jmsv/GSW4tep+R67+IC9kfOzt8Ja3n4kIOoY5IMVazrHGCJkvvWKbDn5HhI7F6D0fidUytZklnW9d4vr+sISbwO2YPV3oIyskP9C/lilxd1SpiRrhOwR52uOz4+gahSeXUMt7GpuqDCRxJ/VfWBuOOVAgMBAAECggEALCGw5CXfei+lHqIpks86ZHGLmdM2wB/njFyByW1+MtZzydLfTtbZSKnxWnX3uhvwQ8wqiyC1JWsyQk5k8qq5HCGwAL/+zJ3Ak8Jt4x8xMct7RWGQnDL1kUxbMfmne7XHZv6ZB7ZANZOMw4QO8waJfYAntdOQftJXPoFhit72rSfSl5zFtzijvXeIwDqvd3wEsIQ8h16zA5m3hJjNY9V03xkkiafPwfHiMqjxI5l6W8pPt8y79k5t2C8hrHeS4KGHNNDip2AEBDAa6vIJtmMw3DtwJE0bWUXAN5A28UEsprs5KOVtzBr2TOPThLN1XaGlwiJ8C+oc7M2eSEwBvNkGywKBgQDwTWGOM5Vqkt0YOffwolSmeSQSjCZ1iQTjkZ3GERV/27YVH5TwagBNaVEIJ5CeO6DzO716iZWYwRbzL7Jk0YhjxpIBrwOORBOfz76xKZQD/4zNQ3nWXDYLiqRV/5uTPXOQBPC0nSa5Lw33n1qb0+t1D036vCgVj6NTJySWOKG/wwKBgQDe9aPxQYwai7+ZJnntGeXmk5Ogfh8uoiJbjjOqEAnytAedK86G7lBpJErnP1DJ75eq4KkUDyJz5G4HS+exNMHwO43ebIjSs7Kf1NxdTw3C9n/AKcMRzvZhfdE1o3bay1pwdgSKA5TiwhqMm1+7kXVwPlGHBCHjwYcnOPSCWI2xxwKBgQCR0OLZv0NzoBq5kLN7OYXUXr4c4x6TQ8nLrZjnj4ZUR6Z9uuRN3oTAdJ/PKvL+kYBhGGcp7ELypnieqNq/gsYYhW4jx2eI9JZT62PzbR98LZ3rEH7mLJ4+8qo15R0qg6eUROsrLhFJXdxD3lbFKBtAtUDEXViVfMvGsYHqBgNgsQKBgGpF35zxR1yn2+2d/2PaglDDawyG0UojEgld4JZhCrzavv5VkR2TnlRfbiyHa3S1dS+H4k+jXyKqcR+dOJSotwBRArBQP29fI/c3OMppEgAqCn6H6Wklox6ZIA1XGyHy5+rO9h7q0h67snfu31TCYp3btnSKrbSn3En/xdwTZYalAoGASadDDf2JdRqNaDb46yJGRohBILrc+LMEzvgdhvLs887GmCeI+EWUfmK01FX33MsPD6ftxd6zIC9nfWFxfmFfilkGHO3S8kJZDq97sw3wvLWuFfhKNG078qOSdiD9iXIyLZDFJzIWyZA0YGHUzh3AmIUv5mJx0eJDWVTSgXT7ML4=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        ports:
        - containerPort: 80
        volumeMounts:
            - name: nginx-index-file
              mountPath: /usr/share/nginx/html/
      volumes:
      - name: nginx-index-file
        configMap:
          name: index-html-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
  tls:
    - hosts:
        - localhost
      secretName: test-tls
