apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-multitool
  labels:
    app: busybox-multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-multitool
  template:
    metadata:
      labels:
        app: busybox-multitool
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ['sh', '-c', 'while true; do date >> /output/output.txt; sleep 5; done']
        volumeMounts:
        - name: pvc-vol
          mountPath: /output
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "1"
      - name: multitool
        image: wbitt/network-multitool
        command: ['sh', '-c', 'while true; do cat /input/output.txt; sleep 10; done']
        volumeMounts:
        - name: pvc-vol
          mountPath: /input
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "1"
      volumes:
      - name: pvc-vol
        persistentVolumeClaim:
          claimName: pvc-busytool
