apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp/pv1
  persistentVolumeReclaimPolicy: Retain
