apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-busytool
spec:
  storageClassName: ""
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
