apiVersion: v1
kind: Pod
metadata:
  name: pod-multitool-v1
  labels:
    app: pod-multitool-v1
spec:
  containers:
    - name: multitool
      image: wbitt/network-multitool
      env:
        - name: HTTP_PORT
          value: "1080"
        - name: HTTPS_PORT
          value: "10443"
