apiVersion: v1
kind: Service
metadata:
  name: service-v2
spec:
  type: NodePort
  selector:
    app: deployment-v1
  ports:
    - name: nginx-http
      port: 9001
      targetPort: 80
      nodePort: 30000
